/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProRouteImport } from './routes/pro'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ProjectNameRouteImport } from './routes/project.$name'
import { Route as ProjectNameTaskKeyRouteImport } from './routes/project.$name.task.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameTaskKeyRoute = ProjectNameTaskKeyRouteImport.update({
  id: '/task/$key',
  path: '/task/$key',
  getParentRoute: () => ProjectNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
  '/project/$name': typeof ProjectNameRouteWithChildren
  '/project/$name/task/$key': typeof ProjectNameTaskKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
  '/project/$name': typeof ProjectNameRouteWithChildren
  '/project/$name/task/$key': typeof ProjectNameTaskKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
  '/project/$name': typeof ProjectNameRouteWithChildren
  '/project/$name/task/$key': typeof ProjectNameTaskKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pro'
    | '/settings'
    | '/event/$id'
    | '/project/$name'
    | '/project/$name/task/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pro'
    | '/settings'
    | '/event/$id'
    | '/project/$name'
    | '/project/$name/task/$key'
  id:
    | '__root__'
    | '/'
    | '/pro'
    | '/settings'
    | '/event/$id'
    | '/project/$name'
    | '/project/$name/task/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRoute
  SettingsRoute: typeof SettingsRoute
  EventIdRoute: typeof EventIdRoute
  ProjectNameRoute: typeof ProjectNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name/task/$key': {
      id: '/project/$name/task/$key'
      path: '/task/$key'
      fullPath: '/project/$name/task/$key'
      preLoaderRoute: typeof ProjectNameTaskKeyRouteImport
      parentRoute: typeof ProjectNameRoute
    }
  }
}

interface ProjectNameRouteChildren {
  ProjectNameTaskKeyRoute: typeof ProjectNameTaskKeyRoute
}

const ProjectNameRouteChildren: ProjectNameRouteChildren = {
  ProjectNameTaskKeyRoute: ProjectNameTaskKeyRoute,
}

const ProjectNameRouteWithChildren = ProjectNameRoute._addFileChildren(
  ProjectNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRoute,
  SettingsRoute: SettingsRoute,
  EventIdRoute: EventIdRoute,
  ProjectNameRoute: ProjectNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
